import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { MAIN_IMAGE_URL } from "../constants";

const Home: NextPage = () => {
  return (
    <MainContainer>
      <Head>
        <title>Futurama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Futurama - the Animation</h1>
        <p>This website contains information about Futurama.</p>
        <p>For more information, Please click on the picture below</p>
        <a href="./info">
          <ImageContainer src={MAIN_IMAGE_URL}></ImageContainer>
        </a>
      </main>
    </MainContainer>
  );
};

const MainContainer = styled.div`
  width: 100%;
  height: 100vh;
  text-align: center;
`;

const ImageContainer = styled.img`
  width: 100%;
  object-fit: contain;
`;
export default Home;
